List<dynamic> pamukkale = [
  ["pamukkale", "Özel Denizli Cerrahi Hastanesi", 10.000000, 10.000000],
  ["pamukkale", "Pamukkale Üniversitesi Hastanesi"],
  ["pamukkale", "ADSH Kıbrıs Şehitleri Semt Pol."],
  ["pamukkale", "Denizli Özel Şifa Hastanesi"],
  ["pamukkale", "Denizli Devlet Hastanesi"],
  ["pamukkale", "Özel Denizli Tekden Hastanesi"],
  ["merkezefendi", "Denizli Özel Egekent Hastanesi"],
  ["merkezefendi", "Denizli Özel Sağlık Hastanesi"],
  ["merkezefendi", "Özel Denipol Hastanesi"],
  ["merkezefendi", "Özel Odak Hastanesi"],
  ["merkezefendi", "Servergazi Devlet Hastanesi"],
  ["Çivril", "Devlet Hastanesi"],
  ["Çivril", "Şehit Hilmi Öz Devlet Hastanesi"],
  ["Acıpayan", "Acıpayam Devlet Hastanesi"],
  ["Tavas", "Tavas Devlet Hastanesi"],
  ["Honaz", "Honaz Devlet Hastanesi"],
  ["Sarayköy", "Sarayköy Devlet Hastanesi"],
  ["Buldan", "Buldan Arif Cerit Devlet Hastanesi"],
  ["Kale", "Kale Devlet Hastanesi"],
  ["Çal", "Çal Devlet Hastanesi"],
  ["Cameli", "Çameli Devlet Hastanesi"],
  ["Serinhisar", "Serinhisar İlçe Devlet Hastanesi"],
  ["Bozkurt", "Bozkurt Aile Sağlık Merkezi"],
  ["Bozkurt", "Toplum Sağlığı Merkezi"],
  ["Güney", "Güney İlçe Devlet Hastanesi"],
  ["Çardak", "Çardak Devlet Hastanesi"],
  ["Bekilli", "Bekilli Toplum Sağlığı Merkezi"],
  ["Babadağ", "Toplum Sağlığı Merkezi"],
  ["Beyağaç", "Beyağaç Toplum Sağlığı Merkezi"],
  ["Baklan", "Toplum Sağlığı Merkezi"],
];
