// KARAKOL //

List<dynamic> karakollar = [
  ["Pamukkale", "Pamukkale İlçe Emniyet Müdürlüğü", 10.000000, 10.000000],
  ["Pamukkale", "Kınıklı Şehitler Polis Merkez Amirliği"],
  ["Pamukkale", "Çevik Kuvvet Şubesi Müdürlüğü Grup Amirliği"],
  ["Pamukkale", "Çınar Polis Merkezi Amirliği"],
  ["Pamukkale", "Bağbaşı Polis Merkezi Amirliği"],
  ["Pamukkale", "Pamukkale Jandarma Karakol Komutanlığı"],
  ["Pamukkale", "Zabıta Karakol Amirliği"],
  ["Merkez Efendi", "Merkezefendi İlçe Emniyet Müdürlüğü"],
  ["Merkez Efendi", "Sevindik Polis Merkezi"],
  ["Merkez Efendi", "Denizli İl Emniyet Çocuk Şube Müdürlüğü"],
  ["Merkez Efendi", "Çınar Polis Merkezi Amirliği"],
  ["Merkez Efendi", "Bereketli Polis Merkezi Amirliği"],
  ["Merkez Efendi", "Pamukkle İlçe Emniyet Müdürlüğü"],
  ["Merkez Efendi", "Merkezefendi İlçe Jandarma Komutanlığı"],
  ["Çivril", "Polis Merkezi Amirliği"],
  ["Çivril", "İlçe Jandarma Komutanlığı"],
  ["Acıpayam", "Acıpayam İlçe Emniyet Müdürlüğü"],
  ["Acıpayam", "Acıpayam K. Yumrutaş Jan. K. K"],
  ["Acıpayam", "Kelekçi Jandarma Karakol Komutanlığı"],
  ["Acıpayam", "Yeşilyuva Jandarma Karakol Komutanlığı"],
  ["Tavas", "Tavas İlçe Emniyet Müdürlüğü"],
  ["Tavas", "Tavas Jandarma Karakolu"],
  ["Tavas", "Karahisar Jandarma Karakol Komutanlığı"],
  ["Sarayköy", " İlçe Emniyet Müdürlüğü"],
  ["Sarayköy", "Polis Karakolu"],
  ["Honaz", "Honaz İlçe Emniyet Amirliği"],
  ["Honaz", "Gürlek Jandarma Karakol Komutanlığı"],
  ["Honaz", "Honaz İlçe Jandarma Komutanlığı"],
  ["Honaz", "Kaklık Jandarma Karakol Komutanlığı"],
  ["Buldan", " İlçe Emniyet Müdürlüğü"],
  ["Buldan ", "İlçe Jandarma Komutanlığı"],
  ["Kale ", "Bölge Trafik Denetleme Amirliği"],
  ["Kale ", "İlçe Emniyet Müdürlüğü"],
  ["Çal İlçe Jandarma Komutanlığı"],
  ["Çal İlçe Emniyet Amirliği"],
  ["Çal Emniyet Müdürlüğü"],
  ["Süller Jandarma Karakol Komutanlığı"],
  ["Çameli", " İlçe Emniyet Amirliği"],
  ["Çameli", " İlçe Jandarma Komutanlığı"],
  ["Serinhisar", "İlçe Emniyet Müdürlüğü"],
  ["Serinhisar", " İlçe Emniyet Amirliği"],
  ["Serinhisar", " İlçe Jandarma Komutanlığı"],
  ["Bozkurt", " İlçe Emniyet Amirliği"],
  ["Güney", "İlçe Emniyet Amirliği"],
  ["Güney", "İlçe Jandarma Komutanlığı"],
  ["Çardak", "İlçe Emniyet Amirliği"],
  ["Çardak", "İlçe Jandarma Komutanlığı"],
  ["Bekilli ", "İlçe Emniyet Amirliği"],
  ["Bekilli ", "İlçe Jandarma Komutanlığı"],
  ["Babadağ", "İlçe Jandarma Komutanlığı"],
  ["Babadağ", " İlçe Emniyet Amirliği"],
  ["Beyağaç ", "İlçe Emniyet Amirliği"],
  ["Beyağaç ", "İlçe Jandarma Komutanlığı"],
  ["Baklan ", "İlçe Jandarma Komutanlığı"],
  ["Baklan ", "İlçe Emniyet Amirliği"],
];
